FROM prom/prometheus:latest
COPY prometheus.yml /etc/prometheus/prometheus.yml
COPY alerts.yml /etc/prometheus/alerts.yml
CMD ["--config.file=/etc/prometheus/prometheus.yml","--storage.tsdb.path=/prometheus"]
